// Browser test of the guide (first sign-in) and of the press contacts editor.
//   BASE=http://localhost:8787 PW=test node test/e2e-cms.mjs
import { chromium } from 'playwright';
import { tmpdir } from 'node:os';
const DIR = (process.env.OUT || tmpdir()) + '/';
const BASE = process.env.BASE || 'http://localhost:8799', PW = process.env.PW || 'test';
const remote = BASE.startsWith('https');
const b = await chromium.launch({ executablePath: process.env.CHROMIUM || undefined, proxy: remote ? { server: process.env.HTTPS_PROXY } : undefined });
const ctx = await b.newContext({ viewport: { width: 1360, height: 900 }, ignoreHTTPSErrors: remote });
const p = await ctx.newPage();
const errs = []; p.on('pageerror', e => errs.push(e.message));
const step = s => console.log('✓', s);
const toast = async (re, t = 60000) => p.waitForFunction(r => new RegExp(r).test(document.getElementById('toast').textContent) && document.getElementById('toast').classList.contains('show'), re.source, { timeout: t });
await p.goto(BASE + '/upload/');
await p.waitForSelector('#login:not([hidden])', { timeout: 60000 });
await p.waitForTimeout(500); await p.screenshot({ path: DIR + '20-login.png' });
await p.fill('#pwd', PW); await p.click('#login-form button');
await p.waitForSelector('#v-help:not([hidden])', { timeout: 60000 });
step('first sign-in opens How it works');
await p.screenshot({ path: DIR + '21-help.png', fullPage: true });
await p.click('#side [data-brand="fiat"]');
await p.waitForSelector('#v-brand:not([hidden])');
await p.reload(); await p.waitForSelector('#v-brand:not([hidden])', { timeout: 60000 });
step('second time: brand view (guide not forced again)');

await p.click('#side [data-go="#cms=contacts"]');
await p.waitForSelector('#cms-list .doc', { timeout: 60000 });
step('contacts listed: ' + await p.locator('#cms-list .doc').count() + ' | ' + await p.textContent('#cms-sub'));
await p.click('#cms-new');
await p.fill('#if-name', 'ZZ Test Contact');
await p.fill('#if-email', 'not-an-email');
await p.click('#i-save');
await p.waitForFunction(() => /email non è valido/.test(document.getElementById('i-err').textContent), null, { timeout: 30000 });
step('email validated');
await p.fill('#if-email', 'zz.test@example.com');
await p.fill('#if-position', 'Press officer');
await p.locator('#if-country .chipbox').first().click();
await p.screenshot({ path: DIR + '22-contact.png' });
await p.click('#i-save');
await toast(/Salvato come bozza/);
step('contact created as draft');
await p.click('#cms-list .doc:has-text("ZZ Test Contact")');
await p.fill('#if-position', 'Head of press');
await p.click('#i-publish');
await toast(/pubblicat/);
await p.waitForFunction(() => /Head of press/.test(document.getElementById('cms-list').textContent));
step('edited and published');
await p.click('#cms-list .doc:has-text("ZZ Test Contact")');
await p.click('#i-unpublish'); await toast(/Ritirato/);
step('unpublished');
await p.click('#cms-list .doc:has-text("ZZ Test Contact")');
await p.click('#i-delete'); await p.click('#c-yes'); await toast(/Eliminato/);
step('deleted, left: ' + await p.locator('#cms-list .doc').count());
await p.fill('#cms-search', 'fiat');
step('search "fiat": ' + await p.locator('#cms-list .doc').count());
await p.setViewportSize({ width: 390, height: 844 });
await p.goto(BASE + '/upload/#help'); await p.waitForSelector('#v-help:not([hidden])', { timeout: 60000 });
step('mobile overflow: ' + await p.evaluate(() => document.documentElement.scrollWidth > innerWidth));
console.log('ERRORS', JSON.stringify(errs));
await b.close();
